version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Moscow
      - TZ=Europe/Moscow

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=54321
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Moscow
      - TZ=Europe/Moscow

  db:
    image: postgres:16-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=54321
      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10